import fetch from 'node-fetch';

/**
 * Expo Snack API integration for React Native code execution
 * Using Expo Snack to provide live preview and emulation
 */

const SNACK_API_URL = 'https://exp.host/--/api/v2/snack';

/**
 * Create a new Expo Snack with the provided code
 * @param {string} code - React Native component code
 * @param {object} options - Additional options
 * @returns {Promise<object>} - Snack details including preview URL
 */
export async function createSnack(code, options = {}) {
  const {
    name = 'React Native Live Code',
    description = 'Generated by MobileDev Portal',
    dependencies = {}
  } = options;

  try {
    // Prepare the snack configuration
    const snackConfig = {
      manifest: {
        name,
        description,
        sdkVersion: '51.0.0', // Latest stable SDK
        dependencies: {
          'expo-status-bar': '*',
          ...dependencies
        }
      },
      code: {
        'App.js': {
          type: 'CODE',
          contents: code
        },
        'package.json': {
          type: 'CODE',
          contents: JSON.stringify({
            dependencies: {
              'expo-status-bar': '~1.12.1',
              'react': '18.2.0',
              'react-native': '0.74.5',
              ...dependencies
            }
          }, null, 2)
        }
      }
    };

    // Create snack via API
    const response = await fetch(`${SNACK_API_URL}/save`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(snackConfig)
    });

    if (!response.ok) {
      throw new Error(`Snack API error: ${response.statusText}`);
    }

    const  result = await response.json();
    
    return {
      success: true,
      id: result.id,
      url: `https://snack.expo.dev/${result.id}`,
      embedUrl: `https://snack.expo.dev/embedded/${result.id}`,
      qrUrl: result.qrUrl || null,
      message: 'Snack created successfully'
    };

  } catch (error) {
    console.error('Error creating Snack:', error);
    return {
      success: false,
      error: error.message,
      message: 'Failed to create Snack preview'
    };
  }
}

/**
 * Alternative: Run React Native code using simple compilation
 * This doesn't require Expo Snack but provides basic syntax validation
 */
export async function validateReactNativeCode(code) {
  try {
    // Basic syntax validation using eval in isolated context
    // This is a simplified version - real validation would use babel or similar
    
    const errors = [];
    const warnings = [];

    // Check for common React Native patterns
    if (!code.includes('import') && !code.includes('require')) {
      warnings.push('No imports detected - make sure to import React and components');
    }

    if (!code.includes('export default')) {
      errors.push('Missing default export for App component');
    }

    // Check for basic React Native components
    const commonComponents = ['View', 'Text', 'StyleSheet', 'Button', 'ScrollView'];
    const usedComponents = commonComponents.filter(comp => code.includes(comp));

    return {
      success: errors.length === 0,
      errors,
      warnings,
      usedComponents,
      linesOfCode: code.split('\n').length
    };

  } catch (error) {
    return {
      success: false,
      errors: [error.message],
      warnings: []
    };
  }
}

/**
 * Generate embeddable preview URL for mobile frame display
 */
export function getEmbedPreviewUrl(snackId, options = {}) {
  const {
    platform = 'web', // 'web', 'ios', or 'android'
    theme = 'light',    // 'light' or 'dark'
    preview = 'true',
    iframeId = null
  } = options;

  const params = new URLSearchParams({
    platform,
    theme,
    preview,
    ...(iframeId && { iframeId })
  });

  return `https://snack.expo.dev/embedded/@snack/${snackId}?${params.toString()}`;
}

/**
 * Create a snack with full example code
 */
export async function createExampleSnack(exampleType = 'basic') {
  const examples = {
    basic: `import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Hello, React Native!</Text>
      <Text style={styles.subtitle}>Welcome to MobileDev Portal</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
  },
});`,

    interactive: `import React, { useState } from 'react';
import { StyleSheet, Text, View, Button, TextInput } from 'react-native';

export default function App() {
  const [name, setName] = useState('');
  const [greeting, setGreeting] = useState('');

  const handlePress = () => {
    setGreeting("Hello" + name + '!');
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Interactive Demo</Text>
      <TextInput
        style={styles.input}
        placeholder="Enter your name"
        value={name}
        onChangeText={setName}
      />
      <Button title="Say Hello" onPress={handlePress} />
      {greeting ? <Text style={styles.greeting}>{greeting}</Text> : null}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  input: {
    width: '100%',
    height: 40,
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginBottom: 15,
    backgroundColor: '#fff',
  },
  greeting: {
    fontSize: 20,
    color: '#007AFF',
    marginTop: 20,
  },
});`
  };

  const code = examples[exampleType] || examples.basic;
  return await createSnack(code, { name: `Example: ${exampleType}` });
}
